"use client"
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import {useEffect, useState} from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

/*export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({ children }) {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [username, setUsername] = useState('');

  const checkAuth = () => {
    const token = localStorage.getItem('token');
    if (token) {
      const savedUsername = localStorage.getItem('username');
      if (savedUsername) {
        setIsLoggedIn(true);
        setUsername(savedUsername);
      }
    } else {
      setIsLoggedIn(false);
      setUsername('');
    }
  };

  useEffect(() => {
    checkAuth();

    const handleAuthChange = () => {
      checkAuth();
    };

    window.addEventListener("authChange", handleAuthChange);

    return () => {
      window.removeEventListener("authChange", handleAuthChange);
    };
  }, []);

  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
    <nav style={{padding: "1rem", backgroundColor: "#f5f5f5"}}>
      <Link href="/">Home</Link> |{" "}
      {isLoggedIn ? (
          <>
            <Link href="logout">Log Out</Link>
            <h4>Welcome, {username}</h4>
          </>
      ) : (
          <>
            <Link href="register">Sign Up</Link> |{" "}
            <Link href="login">Log In</Link>
          </>
      )}
    </nav>
    {children}
    </body>
    </html>
  );
}
