"use client"
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import {useEffect, useState} from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

/*export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({ children }) {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [username, setUsername] = useState('');


  const checkAuth = async () => {
    try {
      const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/auth/status`, {
        method: 'GET',
        credentials: 'include', // Ensure cookies are sent
      });

      if (response.ok) {
        const data = await response.json();
        setIsLoggedIn(true);
        setUsername(data.user.username);
      } else {
        setIsLoggedIn(false);
        setUsername('');
      }
    } catch (error) {
      console.error('Auth check failed:', error);
      setIsLoggedIn(false);
      setUsername('');
    }
  };


  useEffect(() => {
    checkAuth();

    const handleAuthChange = () => {
      checkAuth();
    };

    window.addEventListener("authChange", handleAuthChange);

    return () => {
      window.removeEventListener("authChange", handleAuthChange);
    };
  }, []);

  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
    <nav className="fixed top-0 left-0 w-full z-10 text-white px-10 py-4 flex justify-between items-center" style={{ backgroundColor: "\n" +
          "#2d3f50"}} >
      <Link href="/">Home</Link> |{" "}
      {isLoggedIn ? (
          <>
            <Link href="logout">Log Out</Link>
            <h4>Welcome, {username}</h4>
          </>
      ) : (
          <>
            <Link href="register">Sign Up</Link> |{" "}
            <Link href="login">Log In</Link>
          </>
      )}
    </nav>
    {children}
    </body>
    </html>
  );
}
